# Generated by Django 5.1 on 2024-09-09 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lote', '0001_initial'),
        ('producto', '0002_remove_producto_codigo_invima_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('codigo_barras', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('vendido', 'Vendido'), ('danado', 'Dañado'), ('vencido', 'Vencido')], default='disponible', max_length=10)),
                ('codigo_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lote.lote')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
