# Generated by Django 5.1 on 2024-09-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo_invima',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre_producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='Sin marca', max_length=30),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='Nombre por definir', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(choices=[('Tableta', 'Tableta'), ('Capsula', 'Capsula'), ('Jarabe', 'Jarabe'), ('Suspension', 'Suspension'), ('Inyectable', 'Inyectable'), ('Pomada', 'Pomada'), ('Crema', 'Crema'), ('Gota', 'Gota'), ('Aerosol o inhaladores', 'Aerosol'), ('Inhalador', 'Inhalador'), ('Supositorio', 'Supositorio'), ('Polvo', 'Polvo')], default='Tableta', max_length=25),
        ),
        migrations.AddField(
            model_name='producto',
            name='registro_invima',
            field=models.CharField(default='Desconocido', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
