# Generated by Django 5.1 on 2024-09-08 23:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
    ]
