# Generated by Django 5.1 on 2024-08-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombre_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=2)),
                ('numero_documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('numero_telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
